### PR TITLE
Ir 6 getting intervention incidents

### PR DESCRIPTION
**Pull request by NakagweSharifah**
i implemented the get intervention incidents

### CODE REVIEW

**Review by iandrew8 — APPROVED** [review]

**Review by ttcollins — APPROVED** [review]
Good work @NakagweSharifah

**Comment by ttcollins** [comment]
@NakagweSharifah, you should add the readyforreview label to your PR

**Review by katusiimeconrad — APPROVED** [review]
Looks Good

**Review by fredmugerwa — CHANGES_REQUESTED** [review]
Kindly remove unwanted files
Screen Shot 2021-09-13 at 2 29 08 PM

**Comment by NakagweSharifah** [comment]
> 
> 
> Kindly remove unwanted files
> Screen Shot 2021-09-13 at 2 29 08 PM

ressolved

**Review by reifred — APPROVED** [review]

**Pull request merged**
